backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:

  - name: "videos"
    label: "NeverPaws Videos"
    folder: "videos"
    create: true

    fields:

      - name: "title"
        label: "Video Title"
        widget: "string"

      - name: "youtube"
        label: "YouTube Video ID"
        widget: "string"

      - name: "description"
        label: "Description"
        widget: "text"

      - name: "category"
        label: "Category"
        widget: "select"
        options:
          - "Best of NeverPaws"
          - "Old Videos"
          - "Funny Videos"